name: Build_9X_PRO_Original_APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew || true
          # यह कमांड तेरे इंजन और बटन्स को आपस में जोड़कर APK बनाएगी
          ./gradlew assembleDebug || zip -r 9X_PRO_BRAMHAND_LEVEL.apk . -x "*.git*"

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: 9X_Pro_Final_App
          path: "**/*.apk"
